Fix the version argument to ArgumentParser is deprecated. (#15948)
The "version" argument to ArgumentParser is deprecated. 
Please refer to https://bugs.launchpad.net/yade/+bug/1134422

Take a short example:
```
import argparse
parser = argparse.ArgumentParser(version='1.0')
```
the error result is shown as below:
```
$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    parser = argparse.ArgumentParser(version='1.0')
TypeError: __init__() got an unexpected keyword argument 'version'
```

**Solution**: use `parser.add_argument()` to fix it.

Signed-off-by: Yongtao Huang <yongtaoh@vmware.com>