Add test case for PR-11946 (#16669)
Long log:

This commit adds the test case to verify the code change in PR-11946 .

Long query log will be truncated when writing log.csv. 
UTF-8 is a variable-length encoding of 1~4 bytes, 
so UTF-8 characters may be truncated in the middle.

Without PR-11946, the test case will meet encoding ERROR,
because the long query log is truncated.
```
ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0xa3 0x22
```
please refer to the special char in the log.csv `�` as below:
```
独坐幽篁里弹琴复长啸深林人不知明月来相照
千山鸟�",,,,,"PL/Python function ""elog_test_string_truncate""",
```

Signed-off-by: Yongtao Huang <yongtaoh@vmware.com>