Fix: BaseException.message deprecated since Python 2.6 (#15943)
Long log:

`BaseException.message` was deprecated since Python 2.6 and removed in Python 3.

This is a tiny example:
```
def test_func():
    if 1 == 2:
        allen_dic = {}  # trigger an exception
    allen_dic['allen'] = 'handsome'

try:
    test_func()
except Exception as e:
    raise Exception("Error msg: %s" % e.message)
```

Run the example in _Python3_, error result is shown as below:
```
Traceback (most recent call last):
  File "hello.py", line 9, in <module>
    raise Exception("Error msg: %s" % e.message)
AttributeError: 'UnboundLocalError' object has no attribute 'message'
```

**Solution**: substitute `str(e)` for `e.message`

Signed-off-by: Yongtao Huang <yongtaoh@vmware.com>