Fix ERROR: "Cannot add cell to table content: total cell count of XXX exceeded." (#16388)
When user try to select a big number of rows via PSQL, they may encounter the following error:
ERROR: "Cannot add cell to table content: total cell count of XXX exceeded.

The root cause is the overflow of int type in printTableAddCell().
Fix it in this commit.

(And this issue also exists in upstream, I have reported it:
https://www.postgresql.org/message-id/flat/TYBP286MB0351B057B101C90D7C1239E6B4E2A%40TYBP286MB0351.JPNP286.PROD.OUTLOOK.COM)