Support specification of reloptions when switching storage model
This allow users to specify reloptions when they are switching the
storage model of the table:

ALTER TABLE <> SET ACCESS METHOD <> WITH ([reloptions]);

We also support the legacy `appendonly`/`appendoptimized` options
in the SET WITH clause:

ALTER TABLE <> SET WITH (appendonly|appendoptimized=true|false, [reloptions]);

Examples:
CREATE TABLE tab (a int);
ALTER TABLE tab SET ACCESS METHOD ao_row WITH (blocksize=65536);

or:
ALTER TABLE tab SET WITH (appendonly=true, blocksize=65536);

Note that if a user specifies different access methods in a single
statement, an error will be thrown. E.g.:

ALTER TABLE ataoset SET ACCESS METHOD ao_row WITH(appendonly=true, orientation=column);
ERROR:  ACCESS METHOD is specified as "ao_row" but the WITH option indicates it to be "ao_column"
LINE 1: ALTER TABLE ataoset SET ACCESS METHOD ao_row WITH(appendonly...
                                                     ^

Also, normally access method change requires table rewrite. But
if a user uses the above syntax but specify the same access method
and/or reloptions, we will not do a table rewrite.

Also adjusted the test output of alter_distribution_policy that
the altered reloptions should be shown.