SIGPIPE during ending not exhausted external table scan (#14020)
Executing a query that doesn't fetch all tuples from external scan that execute
program on coordinator leads to the next error:

ERROR:  external table table_master command ended with SHELL TERMINATED by
signal SIGPIPE (13)
DETAIL:  Command: execute:(echo foo; sleep 1; echo bar)

There are several cases when gpdb ends unfinished plan: extended protocol,
cursors. Greenplum communicate with shell command by pipe, it closes pipe while
shell command steel sends results. And SIGPIPE happens here. In such cases
if external web table is executed on segments, then it uses squelching
mechanics, that provides a separate way to handle unfinished yet plan nodes and
simply ignore SIGPIPE for externalScan. But the squelching doesn't execute
for master-only plans on coordinator. So the solution is allowing squelching
on master for such plans.

The condition checking detail is discussed as followed：
1. `Gp_role` is checked because we need squelching on coordinator
2. `es_top_eflags` is checked because `es_got_eos` is not set by explain only.
`es_got_eos` is set to `True` by `ExecutorRun`, which is not called by explain only,
then `ExecutorEnd` tries squelch uninitialized state